name: sample
version: 0.0.0
synopsis: Sample Haskell project
dependencies:
  - base >= 4.9 && <5

library:
  source-dirs: app

executables:
  hello:
    main: app/Main.hs

ghc-options:
  - -Wall
  - -Wno-type-defaults
  - -Wno-name-shadowing

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - ImpredicativeTypes
  - InstanceSigs
  - LambdaCase
  - LexicalNegation
  - MonoLocalBinds
  - MultiWayIf
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
